# Generated by Django 4.2.7 on 2024-02-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_blog", "0001_initial"),
        ("app_clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_list",
            name="user",
            field=models.ManyToManyField(to="app_clients.client"),
        ),
        migrations.AddField(
            model_name="module",
            name="post_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module",
                to="app_blog.post_list",
            ),
        ),
    ]
