# Generated by Django 4.2.7 on 2024-02-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post_list",
            name="visible_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_post_lists", to="app_clients.client"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="visible_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_posts", to="app_clients.client"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="post_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module",
                to="app_blog.post_list",
            ),
        ),
    ]
