# Generated by Django 4.2.7 on 2024-02-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="post_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_blog.post_list"
            ),
        ),
    ]
