# Generated by Django 4.2.7 on 2024-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_resourse_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="resourse/category/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="resourse/document/"),
        ),
    ]
