# Generated by Django 4.2.7 on 2024-02-09 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_comments", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentcourse",
            old_name="user",
            new_name="client",
        ),
    ]
