# Generated by Django 4.2.7 on 2024-02-09 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_comments", "0003_rename_user_commentcourse_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentcourse",
            old_name="client",
            new_name="user",
        ),
    ]
